
SET(GUI_FILES
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGenTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGenTemplate.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGenTemplate.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSizing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSizing.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSizing.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneWarnings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneWarnings.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneWarnings.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/SizeRangeWidget.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/SizeRangeWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/MiddleTruncateDelegate.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/SizeTableGenerator.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/SizeTableGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogValidateMandatory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogValidateMandatory.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogValidateMandatory.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogAttributes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogAttributes.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogAttributes.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddPossibleValues.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddPossibleValues.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddPossibleValues.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddValueToReplace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddValueToReplace.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddValueToReplace.ui
    ${CMAKE_CURRENT_LIST_DIR}/ComboBoxColumnDelegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ComboBoxColumnDelegate.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogSelectValue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogSelectValue.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogEditPrompts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogEditPrompts.h
)
