
SET(GUI_FILES
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.h
    ${CMAKE_CURRENT_LIST_DIR}/MainWindow.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGenTemplate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGenTemplate.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneGenTemplate.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSizing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSizing.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSizing.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneWarnings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneWarnings.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneWarnings.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMarketplaces.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMarketplaces.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneMarketplaces.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePricing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePricing.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PanePricing.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDiscount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDiscount.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneDiscount.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/TreeSkuDiscount.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/TreeSkuDiscount.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/ProgressDialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/ProgressDialog.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/TableCurrencyRates.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/TableCurrencyRates.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/TablePricing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/TablePricing.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneStore.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneStore.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneStore.ui
    ${CMAKE_CURRENT_LIST_DIR}/panes/SizeRangeWidget.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/SizeRangeWidget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/MiddleTruncateDelegate.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/SizeTableGenerator.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/SizeTableGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.h
    ${CMAKE_CURRENT_LIST_DIR}/panes/PaneSettings.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogExtractInfos.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogValidateMandatory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogValidateMandatory.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogValidateMandatory.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogAttributes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogAttributes.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogAttributes.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddPossibleValues.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddPossibleValues.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddPossibleValues.ui
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddValueToReplace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddValueToReplace.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogAddValueToReplace.ui
    ${CMAKE_CURRENT_LIST_DIR}/ComboBoxColumnDelegate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ComboBoxColumnDelegate.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogSelectValue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogSelectValue.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogEditPrompts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogEditPrompts.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogClassificationTypes.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogClassificationTypes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogGenStorefrontImage.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogGenStorefrontImage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogTemuStoreBrands.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogTemuStoreBrands.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogTemuCreateProduct.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogTemuCreateProduct.cpp
    ${CMAKE_CURRENT_LIST_DIR}/DialogKeywordTemplates.h
    ${CMAKE_CURRENT_LIST_DIR}/DialogKeywordTemplates.cpp
)
