SET(SIZECATEGORY_FILES
    ${CMAKE_CURRENT_LIST_DIR}/AbstractSizeCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/AbstractSizeCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ClothingWomenCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/ClothingWomenCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ClothingMenCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/ClothingMenCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShoesWomenCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/ShoesWomenCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ShoesMenCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/ShoesMenCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ClothingKidCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/ClothingKidCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TopMenCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/TopMenCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/TopWomenCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/TopWomenCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RectangleCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/RectangleCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/HeadCategory.h
    ${CMAKE_CURRENT_LIST_DIR}/HeadCategory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/SizingTableTemplateModel.h
    ${CMAKE_CURRENT_LIST_DIR}/SizingTableTemplateModel.cpp
)
