SET(FILLER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/AbstractFiller.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractFiller.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerCopy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerCopy.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerPrice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerPrice.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerSize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerSize.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerTitle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerTitle.h
)
