SET(FILLER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/AbstractFiller.cpp
    ${CMAKE_CURRENT_LIST_DIR}/AbstractFiller.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerCopy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerCopy.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerPrice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerPrice.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerSize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerSize.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerSelectable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerSelectable.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerTitle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerTitle.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerBulletPoints.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerBulletPoints.h
    ${CMAKE_CURRENT_LIST_DIR}/FillerText.cpp
    ${CMAKE_CURRENT_LIST_DIR}/FillerText.h
)
